### ISSUE TITLE
placeholder support

### ISSUE THREAD

**Issue by jamaluddinrumi** [ascorbic/unpic-img#14]
**Is your feature request related to a problem? Please describe.**
It's important to show our visitor the image is still loading. Hence, adding placeholder which can fiiled with animated svg would be nice for our visitors.

**Describe the solution you'd like**
[Nuxt Image Placeholder](https://image.nuxtjs.org/components/nuxt-img#placeholder)-like would be nice if added here.

**Comment by ascorbic** [comment]
The main reason I've not added comprehensive placeholder support is because I don't want to have any runtime js. What it does support is background=auto, which generates a low-res blurred background placeholder. You can also pass in a CSS colour or a data uri, which could be a traced svg

**Comment by jamaluddinrumi** [comment]
sorry, for late response

yeah, i see 

honestly, i think unpic with no-runtime-js phylosophy would be popular img library for most frontend framework
