### ISSUE TITLE
src gets double transformed with srcset

### ISSUE THREAD

**Issue by colbyfayock** [ascorbic/unpic-img#152]
## Describe the bug

During `transformProps`, the `src` is first transformed with the results overwriting `src`, then transformed a second time as part of `getSrcSet`.

https://github.com/ascorbic/unpic-img/blob/62788fc1fbf4649d0436f8f70df1b9d6898ef988/packages/core/src/core.ts#L422-L427

This works when passing in a standard URL format, but if passing in an ID such as `my-cool-image`, it ends up creating an issue where the base URL is applied twice.

Example:
```
https://res.cloudinary.com/example/image/upload/c_limit,w_750/f_auto/q_auto/https://res.cloudinary.com/example/image/upload/c_limit%252Cw_800/f_auto/q_auto/cld-sample-5%3F_a%3DATFGlAA0
```

## Use Case

My use case here is using a custom transformer to perform my own operations for constructing a URL:

```
<Image
  src="cld-sample-5"
  layout="constrained"
  width={800}
  height={600}
  alt="A lovely bath"
  transformer={({url, width, height,}) => {
    return constructCloudinaryUrl({
      options: {
        src: url,
        width,
        height
      },
      config: {
        cloud: {
          cloudName: 'example'
        }
      }
    });
  }}
/>
```

The produced `src` attribute is accurate on that first run, but all srcset URLs have an issue.

I know this isn't the primary use case but from what I can tell, I'm not seeing any actual benefit of having that second pass of the transformer

## Example Output

```
<img alt="A lovely bath" loading="lazy" decoding="async" sizes="(min-width: 800px) 800px, 100vw" style="object-fit:cover;max-width:800px;max-height:600px;aspect-ratio:1.3333333333333333;width:100%" srcset="https://res.cloudinary.com/example/image/upload/c_limit,w_640/f_auto/q_auto/https://res.cloudinary.com/example/image/upload/c_limit%252Cw_800/f_auto/q_auto/cld-sample-5%3F_a%3DATFGlXu0 640w,
https://res.cloudinary.com/example/image/upload/c_limit,w_750/f_auto/q_auto/https://res.cloudinary.com/example/image/upload/c_limit%252Cw_800/f_auto/q_auto/cld-sample-5%3F_a%3DATFGlXu0 750w,
https://res.cloudinary.com/example/image/upload/c_limit,w_800/f_auto/q_auto/https://res.cloudinary.com/example/image/upload/c_limit%252Cw_800/f_auto/q_auto/cld-sample-5%3F_a%3DATFGlXu0 800w,
https://res.cloudinary.com/example/image/upload/c_limit,w_828/f_auto/q_auto/https://res.cloudinary.com/example/image/upload/c_limit%252Cw_800/f_auto/q_auto/cld-sample-5%3F_a%3DATFGlXu0 828w,
https://res.cloudinary.com/example/image/upload/c_limit,w_960/f_auto/q_auto/https://res.cloudinary.com/example/image/upload/c_limit%252Cw_800/f_auto/q_auto/cld-sample-5%3F_a%3DATFGlXu0 960w,
https://res.cloudinary.com/example/image/upload/c_limit,w_1080/f_auto/q_auto/https://res.cloudinary.com/example/image/upload/c_limit%252Cw_800/f_auto/q_auto/cld-sample-5%3F_a%3DATFGlXu0 1080w,
https://res.cloudinary.com/example/image/upload/c_limit,w_1280/f_auto/q_auto/https://res.cloudinary.com/example/image/upload/c_limit%252Cw_800/f_auto/q_auto/cld-sample-5%3F_a%3DATFGlXu0 1280w,
https://res.cloudinary.com/example/image/upload/c_limit,w_1600/f_auto/q_auto/https://res.cloudinary.com/example/image/upload/c_limit%252Cw_800/f_auto/q_auto/cld-sample-5%3F_a%3DATFGlXu0 1600w" src="https://res.cloudinary.com/example/image/upload/c_limit,w_800/f_auto/q_auto/cld-sample-5?_a=ATFGlXu0">
```

### Work with it as is

I could theoretically construct my image first then pass that in:
```
const url = constructCloudinaryUrl({
  options: {
    src: 'cld-sample-5',
    width: 800,
    height: 600
  },
  config: {
    cloud: {
      cloudName: 'example'
    }
  }
})

<Image
  src={url}
  layout="constrained"
  width={800}
  height={600}
  alt="A lovely bath"
/>
```

This seems to work, but then in my mind it's doing double the work, where really i want to use my own transformer logic, and unpic will always sit on top of that

### Prevent a 2nd pass of src

Move the `src` transformation:

https://github.com/ascorbic/unpic-img/blob/62788fc1fbf4649d0436f8f70df1b9d6898ef988/packages/core/src/core.ts#L422-L425

Below the `srcSet`:

https://github.com/ascorbic/unpic-img/blob/62788fc1fbf4649d0436f8f70df1b9d6898ef988/packages/core/src/core.ts#L426

This works and doesn't break any tests (but maybe we should write a test for that?)

Unscientifically test this by hacking at the `node_modules` directory in a sample Next.js app with React

## To Reproduce

Pass in a non-URL as the `src` with a custom transformer:

```
import { constructCloudinaryUrl } from '@cloudinary-util/url-loader';

<Image
  src="cld-sample-5"
  layout="constrained"
  width={800}
  height={600}
  alt="A lovely bath"
  transformer={({url, width, height,}) => {
    return constructCloudinaryUrl({
      options: {
        src: url,
        width,
        height
      },
      config: {
        cloud: {
          cloudName: 'example'
        }
      }
    });
  }}
/>
```

## Expected behavior

the resulting URL wouldn't be double-"transformed" or at least not create a URL issue

## Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 111.0.5563.64 (Official Build) (arm64)

**Comment by colbyfayock** [comment]
Created a PR in case we're down for this change!

https://github.com/ascorbic/unpic-img/pull/155

**Comment by ascorbic** [comment]
This is fixed in the latest release. Thanks, @colbyfayock!
