### ISSUE TITLE
React: "Warning: Invalid DOM property `srcset`. Did you mean `srcSet`?"

### ISSUE THREAD

**Issue by JannikWempe** [ascorbic/unpic-img#2]
I currently see this waring using `@unpic/react`.

```
Warning: Invalid DOM property `srcset`. Did you mean `srcSet`?
```

It seems the native HTML image props are not transformed into valid JSX image props.

It is still functional though.

**Comment by ascorbic** [comment]
I'm not sure exactly which framework uses which. The solution would probably be just to  remove that logic from unpic and assign it manually in @unpic/react. When I wrote that I was still trying to avoid any framework-specific logic, but I've had to do that for styles now so I think it's fine

**Comment by JannikWempe** [comment]
@ascorbic Thanks for fixed this issue.

Probably the exact same thing happens with `fetchPriority`:

```
Warning: Invalid DOM property `fetchpriority`. Did you mean `fetchPriority`?
```

**Comment by ascorbic** [comment]
@JannikWempe Thanks for the report. I've added a fix for that
