### ISSUE TITLE
Malformed data-attributes

### ISSUE THREAD

**Issue by th-km** [ascorbic/unpic-img#215]
**Describe the bug**
When passing data attributes, the output is either ignored (passing boolean) or malformed.

**To Reproduce**
[CodeSandbox repro](https://codesandbox.io/s/unpic-data-attribute-issue-c7cq3h)

**Expected behavior**
Any props supported by the `<img>` tags can be passed in and should work as expected.

**Screenshots**
![CleanShot 2023-05-10 at 11 36 54@2x](https://github.com/ascorbic/unpic-img/assets/35410212/6f0fe0e4-0c43-41ce-96c0-b33135f79b89)

**Comment by ascorbic** [comment]
Thanks for the report! I have a fix ready now
