### ISSUE TITLE
Export `ImageProps` in `index.ts`

### ISSUE THREAD

**Issue by ahnpnl** [ascorbic/unpic-img#227]
**Is your feature request related to a problem? Please describe.**
Hi, I'm trying to make a wrapper component around `Image`. My wrapper component has some props and I want to construct props for `Image` component based on my wrapper component props. However because `ImageProps` is not exported so it's not so convenient for typescript to get autocomplete.

**Describe the solution you'd like**
Add export for `ImageProps` to https://github.com/ascorbic/unpic-img/blob/main/packages/qwik/src/index.ts

**Describe alternatives you've considered**
**N.A.**

**Additional context**
**N.A.**

**Comment by ascorbic** [comment]
Good idea. I'll do that. In the meantime, you can define it yourself like this:
```ts
import type { QwikIntrinsicElements } from "@builder.io/qwik";
import type { UnpicImageProps } from "@unpic/core";
export type ImageProps = UnpicImageProps<QwikIntrinsicElements["img"]>;
```
