### ISSUE TITLE
srcset attribute is broken in version 0.0.23 with Directus cdn

### ISSUE THREAD

**Issue by Tonton-Blax** [ascorbic/unpic-img#228]
**Describe the bug**
```srcset``` attribute is broken in version 0.0.23 of ```unpic/svelte``` with Directus cdn, worked in version 0.0.22.
Instead of desugaring to multiple comma separated sources in the srcset attribute, it fallbacks to a single src attribute.

**To Reproduce**
1. Just duplicate the basic svelte/unpic component example and provide a Directus url
2. Set the ```cdn``` prop to ```Directus```

**Expected behavior**
srcset attribute should be rendered with multiple sources

**Desktop (please complete the following information):**
- osX 13.3.1 - all browsers

**Additional context**
Note that the src passed to the component is still parsed and processed since it adds a ```?width``` query string at the end.

**Comment by ascorbic** [comment]
Hi
Can you share the actual code? I tried this and it worked fine:

```svelte
<Image
  src="https://apollo.kazel.academy/assets/6d910d38-0659-49bf-80b8-fa6e0b257975"
  cdn="directus"
  layout="constrained"
  width={800}
  height={600}
  alt="Lights"
/>
```

**Comment by ascorbic** [comment]
Note that the `cdn` value needs to be `directus` not `Directus`

**Comment by Tonton-Blax** [comment]
- Ok so I just tried with the exact same code you just posted, see below the resulting img srcset with v0.22:

![v022](https://github.com/ascorbic/unpic-img/assets/6137156/26fdc9d3-9642-4c04-9e92-39557128c7bc)

- And now with v0.23:

![v023](https://github.com/ascorbic/unpic-img/assets/6137156/f5d8a375-dba4-4ac1-9fe1-e05b3e3d161e)

I'm going to try within a fresh new svelte project in case there would be some mojo conflict with another dependency but it doesn't look like it

**Comment by Tonton-Blax** [comment]
Same problem in a [fresh project](https://stackblitz.com/edit/vitejs-vite-zfpgyk?file=src/App.svelte) (Stackblitz)

**Comment by ascorbic** [comment]
Thanks! I've reproduced the issue and have a fix ready

**Comment by Tonton-Blax** [comment]
Wow that was fast, thanks!
