### ISSUE TITLE
Requirement to add external hostnames to Next.js config

### ISSUE THREAD

**Issue by DestroyerXyz** [ascorbic/unpic-img#232]
**Describe the bug**
Hostnames for images loaded from external sites need to be declared in Next.js config.
Not doing so prevents the image from loading and doesn't produce an error, unlike next/image.

**To Reproduce**
1. Create a fresh Next.js project
2. Add an <Image/> with src as any external URL.
3. Image does not load.

**Expected behavior**
An error occurs telling the user to add the image hostname to the Next config.
Similar to [next/image](https://nextjs.org/docs/messages/next-image-unconfigured-host).

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 113

**Comment by ascorbic** [comment]
Thanks for the report. I've implemented this now, so you should get an error when running in development. Upgrade to the latest version to see
