### ISSUE TITLE
Src is required to be a CDN URL for srcset generation

### ISSUE THREAD

**Issue by colbyfayock** [ascorbic/unpic-img#275]
**Description**

We're currently attempting to use the `transformer` prop as the mechanism to construct URLs using our own utilities.

When doing this, we're using the `src` attribute as a public ID, where the API of the component we're building does just that, so we're passing that value in, and allowing the transformer to piece together the src (Public ID), width, and height, along with some other props, to construct the URL.

The issue we're running into is by not passing in a fully formed CDN URL into the `src` prop, we seem to be bypassing the srcset generation, at least thats my current suspicion.

https://github.com/ascorbic/unpic-img/blob/main/packages/core/src/core.ts#L296

That said, if we pass in a constructed base URL into the `src` then still define our custom transformer for the rest of the generated URLs, we seem to get a working version.

This isn't necessarily the way this component was designed to be used, but I'm curious if this use case is able to be satisfied by recognizing a custom defined transformer that wouldn't require a canonical URL.

While this would immediately help my use case, I could also see this able to give more flexibility for using the component for custom patterns that might not make it as part of official support, though I recognize that's certainly an edge case.

Here's the current code that we're working with:

https://github.com/cloudinary-community/svelte-cloudinary/pull/16/files#diff-3563ec9de2b673c6456b0e69471f7845227183497dada6a5bb2d503d98ea0d8bR71

**To Reproduce**

Our ideal Unpic component code would look along the lines of:

```
<Image
  src="myid"
  width="600"
  height="600"
  alt="Text"
  transformer={({ width, height, url }) => {
    return imageFunction({
      src: url, // "myid"
      width,
      height,
      ...extraProps
    })
  }}
/>
```

This however does not generate a srcset.

<img width="1452" alt="image" src="https://github.com/ascorbic/unpic-img/assets/1045274/d87f5014-acfc-4abf-99d0-968844629044">

**Possible Solution**

Given this line will use either the custom passed in `transformer` or find the appropriate one:

https://github.com/ascorbic/unpic-img/blob/main/packages/core/src/core.ts#L302C3-L302C49

If the `transformer` prop is indeed custom, the canonical check could be skipped.

Could be something along the lines of:

```
  const canonical = getCanonicalCdnForUrl(src, cdn);

  // No canonical URL found and there is NOT a custom transformer to satisfy it

  if (!canonical && !transformer) { 
    return;
  }

  transformer ||= getTransformer(canonical.cdn);

  if (!transformer) {
    return;
  }
```

**Comment by ascorbic** [comment]
I think this is a reasonable feature to add. What needs to happen is that we need to implement `delegateUrl` in the Cloudinary transformer, and then add Cloudinary to `delegators` in https://github.com/ascorbic/unpic/blob/main/src/canonical.ts#L7-L10. The transformer needs to delegate any hosts that are on another CDN, but will act as the fallback for any other URL. This is what I've done for next/image and would like to add for others that support remote image loading. That will mean that `getCanonicalCdnForUrl` always returns a valid response.

**Comment by ascorbic** [comment]
It's basically just this that you need to do, so it might be best to extract that into utils, and then re-export it from transformers that use it. https://github.com/ascorbic/unpic/blob/main/src/transformers/vercel.ts#L29-L43

**Comment by colbyfayock** [comment]
i think i understand what you're going for, but are you moreso speaking towards passing in a remote URL as the source? like this test case? https://github.com/ascorbic/unpic/blob/main/src/transformers/vercel.test.ts#L20

in what i consider to be my ideal case, wouldn't that `getCanonicalCdnForUrl` still fail?

given the code: 
```
export function getCanonicalCdnForUrl(
  url: string | URL,
  defaultCdn?: ImageCdn | false,
): CanonicalCdnUrl | false {
  const cdn = getImageCdnForUrl(url) || defaultCdn;
  if (!cdn) {
    return false;
  }
  const maybeDelegated = getDelegatedCdn(url, cdn);
```

if i'm passing in my URL as `image/turtle` for instance (the public ID):

```
<Image src="images/turtle" ... />
```

wouldn't it still not find a CDN and bail early?

im trying to look at that Next.js example you have too, and that looks along the lines of what i need i think since its passing in a non-URL string: https://github.com/ascorbic/unpic/blob/main/src/transformers/nextjs.test.ts#L24

trying to both think and walk through this, woudl i need to pass a `cdn="cloudinary"` maybe so that it gets to the delegation function?

one thing that im thinking this also wouldn't allow me to support is custom cnames, as it would require the res.cloudinary.com URL pattern id think

**Comment by ascorbic** [comment]
The idea would be that you'd need to set the cdn manually. You could then pass in any URL and if it wasn't e.g. a Contentful URL or Unsplash or whatever it would be handled by the Cloudinary transformer, so a CNAME would be fine.

**Comment by colbyfayock** [comment]
it looks like actually setting `cdn="cloudinary"` manually makes the custom transformer "just work" for the srcset part, so i think this is a non-issue anymore unless you see another thread to pull on

going to test this a little more to make sure we're good

**Comment by sicknarlo** [comment]
I think this issue is related [this change](https://github.com/ascorbic/unpic-img/commit/8e87af3db917784069592f0deaa96d016979fc17#diff-f63fb32fca85d8e177d6400ce078818a4815b80ac7a3319b60d3507354890992R298)

I am trying to use Unpic with a custom transformer for an unsupported CDN and it does not generate a `srcset` unless a canonical CDN is found. If I go back to `0.0.20` it works, but the latest (`0.0.29`) does not generate one.

Maybe it's intentional but it seems counterintuitive since a custom transformer is accepted as a prop, and not allowing custom transformers feels like it unnecessarily limits the library. Hoping this is a bug.

**Comment by ascorbic** [comment]
Yeah, that is a fair point. So perhaps a custom transformer should disable auto-detection entirely
