### ISSUE TITLE
Wong computation of `lowResHeight`

### ISSUE THREAD

**Issue by aurelienbobenrieth** [ascorbic/unpic-img#279]
There is an issue in the computation of the `lowResHeight` with `aspectRatio`. There is a multiplication whereas it should be a division.

https://github.com/ascorbic/unpic-img/blob/main/packages/core/src/core.ts#L404

(pretty much just like it's done there: https://github.com/ascorbic/unpic-img/blob/main/packages/core/src/core.ts#L384)

```typescript
    const lowResHeight = aspectRatio
      ? Math.round(LOW_RES_WIDTH * aspectRatio) // ❌
      : undefined;
```

should be

```typescript
    const lowResHeight = aspectRatio
      ? Math.round(LOW_RES_WIDTH / aspectRatio) // ✅
      : undefined;
```

Given a width of 24 and an aspect ratio of 16/9, the height should be 13.5 and not 42.6 (like it is actually returned) else the aspect ratio is reversed.

**Comment by ascorbic** [comment]
Clsoed in https://github.com/ascorbic/unpic-img/pull/280
