### ISSUE TITLE
Disable console.error message

### ISSUE THREAD

**Issue by johannesschaffer** [ascorbic/unpic-img#34]
**Describe the bug**
Most of the time I can't set the width, height or aspect-ratio via component props (React version), since they are based on media queries. It however still works when set via CSS. The logging of the errors however makes the Image basically unusable since it clutters completely the dev tools with multiple images on a page

**Comment by ascorbic** [comment]
The image URL generator needs the width and/or height to generate the correct srcset, so you should still pass it in and it is an error if you don't. You can override the actual sizes with CSS if you want (use `!important` to override the inline styles).
