### ISSUE TITLE
Module not found with Next.js 14

### ISSUE THREAD

**Issue by DestroyerXyz** [ascorbic/unpic-img#355]
**Describe the bug**
The same as #118 with a different cause.

Seems like this is caused by Next changing the `next/dist/shared/lib/image-config-context.js` file to `next/dist/shared/lib/image-config-context.shared-runtime.js`.

Changing that seems to fix it.

I'm not sure when this might have happened but might be Next 14.

**Comment by ascorbic** [comment]
Ah, Next.js, changing everything every time. Thanks for the heads-up. I'll take a look.

**Comment by DestroyerXyz** [comment]
Hey!
Any updates on this?
I can open a PR but I'm guessing there needs to be some extra work to keep compatibility with older Next versions?

**Comment by ascorbic** [comment]
Yeah, that's the delay. Considering whether to just make it a breaking change.

**Comment by ascorbic** [comment]
I have a release that handles this. It's a breaking change with a new import subpath. 

Separately I have opened a discussion on the Next.js repo, asking this to be made a public API so it doesn't break again.

https://github.com/vercel/next.js/discussions/58532

**Comment by clementoriol** [comment]
Just FYI, the changed happened before next@14, at next@13.4.20-canary.20 :

https://github.com/vercel/next.js/commit/a5b7c77c1ff0096af7609a8bfc1e064d30db4e30
https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.20

So if you're using next@13.4.20 or newer, you'll need to use "@unpic/react/nextjs"
