### ISSUE TITLE
Support for `styles` attribute in @unpic/react

### ISSUE THREAD

**Issue by luqven** [ascorbic/unpic-img#360]
Hey there, first and foremost thank you for maintaining this fantastic library!

I stumbled on this small issue and I had some ideas about potential work arounds that might benefit other folks as well.

**Is your feature request related to a problem? Please describe.**
Using the `style` attribute in React throws TS errors.

```tsx
<Image
  {/* 
    Type '{ src: string; height: number; width: number; style: { objectFit: string; }; alt: string; }' 
    is not assignable to type 'IntrinsicAttributes & (ImageProps & RefAttributes<HTMLImageElement>)'.
  */}
  style={{objectFit: 'cover'}}
  width={500}
  height={300}
  layout="constrained"
  src={src || placeholder}
/>
```
This does, however, apply the desired styles.

**Describe the solution you'd like**
What I'd like to do is extend the prop types definition to include `React.CSSProperties` so that I don't get TS errors when using those attributes

```tsx
// packages/react/src/image.tsx

import * as React from "react";
import { transformProps, UnpicImageProps } from "@unpic/core";
import { camelizeProps } from "./camelize";

export type ImageProps = UnpicImageProps<
  React.ImgHTMLAttributes<HTMLImageElement>
> & {style: React.CSSProperties}

export const Image = React.forwardRef<HTMLImageElement, ImageProps>(
  function Image(props, ref) {
    const {style, ...rest} = props;
    const transformedProps = transformProps(rest);
    const camelizedProps = camelizeProps(transformedProps as React.ImgHTMLAttributes<HTMLImageElement>);
    return <img {...camelizedProps} ref={ref} style={style}/>;
  },
);

```

**Describe alternatives you've considered**
An alternative would be to support styling the underlying element with the undocumented `objectFit` prop when there is no `transformer` present.

```ts
// packages/core/src/core.ts

// If the objectFit prop is set and there's no transformer, add the style
  if (objectFit && !transformedProps.style) {
    transformedProps = {
      ...transformedProps,
      style: {['object-fit']: objectFit},
    }
  }

  return {
    ...transformedProps,
    src: url?.toString(),
    width,
    height,
  } as TImageAttributes;
}
```

**Additional context**
The reason I'd like to be able to do this is to set `objectFit` to contain for `blob:` URLs. This way, I can use a single `<Image>` component for previewing and displaying image uploads.

```tsx
// FileUpload.tsx

import { useState } from "react";
import { Image } from "@unpic/react";


function FileUploadForm() {
  const [file, setFile] = useState<File | null>(null);
  // ...
  return (
    <div>
      <form style={{paddingBottom: 50}} onSubmit={handleSubmit}>
        <input
          type="file"
          name="file"
          accept="image/*"
          onChange={handleFileChange}
        />
        <button type="submit">Upload File</button>
      </form>
      <div>{status}</div>
      {src || placeholder && <Image
          style={{objectFit: 'cover'}}
          width={500}
          height={300}
          layout="constrained"
          src={src || placeholder}
        />}
    </div>
  );
}

export default FileUploadForm;
```
---
Thanks for taking the time to read this issue! This is a niche use-case, so I'm more than happy to close this if you all consider this to be out-of-scope.

**Comment by ascorbic** [comment]
Thanks for the report. I've done an update that does both: it applies the standard styles, even if the image is not transformed, as well as passing down any user-specified styles.
