### ISSUE TITLE
Angular: Add standalone versions of Unpic directives

### ISSUE THREAD

**Issue by brandonroberts** [ascorbic/unpic-img#365]
**Is your feature request related to a problem? Please describe.**

The `UnpicModule` is used to import the UnpicImageDirective and UnpicSourceDirective directives

**Describe the solution you'd like**

The UnpicImageDirective and UnpicSourceDirective directives are exported as standalone directives that can also be used inside the UnpicModule. 

Standalone components/pipes/directives have been out since Angular v14 and are the default and recommended way going forward.

This would be solved by adding `standalone: true` to the directive decorator metadata, and moving the directives from the `declaratations` array in the `UnpicModule` to the `imports` array.

The `exports` array would remain the same. The public API would remain the same also.

**Describe alternatives you've considered**

**Additional context**

**Comment by ascorbic** [comment]
Hah. So basically the opposite of what I did here? https://github.com/ascorbic/unpic-img/pull/328/files#diff-48e6b8b2e45d5e1a8afe892da600bdf0a9ee831dee028e354910347178f13bf6

**Comment by brandonroberts** [comment]
Yep 😄

**Comment by ascorbic** [comment]
So would I need to remove the module at that point? I'm trying to work out the best way to be backwards-compatible?

**Comment by ascorbic** [comment]
Or you're saying it's ok to still export `UnpicModule` with standalone directives if they're in the imports array instead?

**Comment by brandonroberts** [comment]
Yes, its ok to still export it. Keep the `UnpicModule` and move the standalone directives in the `imports` array.

**Comment by nartc** [comment]
Yes, so it would look something like this

```diff
@Directive({
+ standalone: true
})
export class UnpicImageDirective {}

@Directive({
+ standalone: true
})
export class UnpicSourceDirective {}

@NgModule({
- declarations: [UnpicImageDirective, UnpicSourceDirective],
+ imports: [UnpicImageDirective, UnpicSourceDirective],
  exports: [UnpicImageDirective, UnpicSourceDirective]
})
epoxrt class UnpicModule {}
```

**Comment by brandonroberts** [comment]
Yep, exactly

**Comment by ascorbic** [comment]
Nice. Thanks both! While Angular 2 was my first modern frontend framework (and the reason I learnt TypeScript), it is very rusty.

**Comment by ascorbic** [comment]
A review on #366 would be appreciated!
