### ISSUE TITLE
Sync astro npm and git versions

### ISSUE THREAD

**Issue by jlarmstrongiv** [ascorbic/unpic-img#422]
The latest @unpic/astro version on GitHub is 0.0.37

https://github.com/ascorbic/unpic-img/releases/tag/astro-v0.0.37

The latest @unpic/astro version on npm is 0.0.36

https://www.npmjs.com/package/@unpic/astro

**Comment by ascorbic** [comment]
AH, thanks for spotting that. Looks like release-please failed. I've done a manual publish.
