### ISSUE TITLE
Transform URLs seem to flip height and width

### ISSUE THREAD

**Issue by MaxMonteil** [ascorbic/unpic-img#53]
**Describe the bug**
When using the `Image` component as described in the docs, the image comes out distorted and the `srcset` urls seem to have their width and height values flipped.

I only got to try it with Cloudinary.

**To Reproduce**
Go to [https://stackblitz.com/edit/nuxt-starter-rct4hw?file=app.vue](https://stackblitz.com/edit/nuxt-starter-rct4hw?file=app.vue)

**Expected behavior**
I expected the image to respect the width and height attributes without appearing distorted.

**Comment by jahirfiquitiva** [comment]
I'm facing a similar issue with the `react` package. I think the requested image swaps `width` and `height` based on the request image.

This is the rendered image component:
<img width="202" alt="Shot 2023-02-28 at 19 26 23@2x" src="https://user-images.githubusercontent.com/10360816/222014518-3d557ed8-3c7d-4ff0-8e69-27299ad7c061.png">

This is the requested image:
<img width="542" alt="Shot 2023-02-28 at 19 32 36@2x" src="https://user-images.githubusercontent.com/10360816/222014621-af0f23c5-a8f8-4c64-bf2c-17d2babc4b20.png">

This is the original image:
![Healthcare](https://user-images.githubusercontent.com/10360816/222014679-9bd6ea34-093c-4ad7-a8da-ba4b51871967.jpg)

And these are the image details from Contentful (which is what I'm using):
<img width="750" alt="Shot 2023-02-28 at 19 30 57@2x" src="https://user-images.githubusercontent.com/10360816/222014719-8a753ae4-c9d8-441a-8e89-1fceb904b8bd.png">

**Comment by ascorbic** [comment]
Hmm. I thought I'd fixed it with the recent unpic release. I'll see what's up.

**Comment by ascorbic** [comment]
Thanks @ruijdacd for the fix! If you update to the latest version it should work in all packages now
