### ISSUE TITLE
Avoid prefix with URL origin for Vercel image optimization 

### ISSUE THREAD

**Issue by maiertech** [ascorbic/unpic-img#744]
**Describe the bug**

I use `@unpic/svelte` in a SvelteKit app deployed to Vercel. My deploy previews are access protected, i.e. you need to be logged in to see the preview.

I provide to `Image` a `src` with a relative URL `/_vercel/image?url=${src}&q=${quality}` with the querystring `src` being a **relative** URL generated by Vite.

On the server-rendered page source I see in the `srcset` URLs like this one (shown decoded)

```
/_vercel/image?url=/_app/immutable/assets/mike-van-den-bos-fbQv3cx--bM-unsplash.a5Y7YFW3.jpg&q=80&w=768
```

exactly how I expected it. The Vercel image optimization API can deal with relative URLs provided to `url`, so the above relative URL would render fine, even in an access protected deploy preview.

Let's start with what I see when JavaScript is turned off, i.e. the browser renders the server-side rendered page:

![js-off](https://github.com/user-attachments/assets/04e74218-b010-4e13-bd81-d5b25b292ea0)

Works as expected, all good. But when I turn on JavaScript, I see a broken image:

![js-on](https://github.com/user-attachments/assets/fd0ca5e0-d708-47b1-8530-036473378bc6)

Chrome dev tools reveal that when JavaScript is on, instead of this type of URL

```
/_vercel/image?url=/_app/immutable/assets/mike-van-den-bos-fbQv3cx--bM-unsplash.a5Y7YFW3.jpg&q=80&w=768
```

I see URLs prefixed with the origin

```
/_vercel/image?url=https://sveltekit-helpers-git-maiertech-issue221-maierlabs.vercel.app/_app/immutable/assets/mike-van-den-bos-fbQv3cx--bM-unsplash.a5Y7YFW3.jpg&q=80&w=768
```

So the image optimization API tried to optimize `https://sveltekit-helpers-git-maiertech-issue221-maierlabs.vercel.app/_app/immutable/assets/mike-van-den-bos-fbQv3cx--bM-unsplash.a5Y7YFW3.jpg`, which it considers an external image, instead of relative image `/_app/immutable/assets/mike-van-den-bos-fbQv3cx--bM-unsplash.a5Y7YFW3.jpg`.

And because my deploy preview is access protected the image optimization API cannot access the fully qualified URL and throws a 502 `OPTIMIZED_EXTERNAL_IMAGE_REQUEST_UNAUTHORIZED` resulting in a broken image.

If the deploy preview was not access protected all would work as expected because adding the origin to the `url` querystring would not cause any harm. But with access protection on it breaks the image.

I am not sure where exactly the origin gets added, but I wonder if this behavior can be turned off. Meaning `Image` uses whatever it is provided and does not alter the `url` querystring.

**Comment by ascorbic** [comment]
Interesting. I'm not sure where it gets added either. I will try and look into it, but it may be a few weeks before I get the chance. If you could take a look yourself then that would be great! I'd be happy to merge any fix, or just make a change if you can find the source of the bug.

**Comment by maiertech** [comment]
The issue is probably related to the Vercel transformer in `unpic`: https://github.com/ascorbic/unpic/blob/main/src/transformers/vercel.ts. It calls a `toUrl` in `parse`. But have not fully understood where the origin gets added.

**Comment by ascorbic** [comment]
`toUrl` should retain relative URLs, which is why it's used instead of a URL constructor.

**Comment by maiertech** [comment]
Your comment made me doubt that this issue is caused by `unpic`.

The uBlock Origin Lite extension in Chrome seems to rewrite the URLs inside the `srcset` (for whatever reason). When I bump down the agressiveness of how it filters, I see relative URLs and images render as expected.

Sorry for the false positive, and thanks for your input!
