### ISSUE TITLE
[Vue warn]: Do not use built-in or reserved HTML elements as component id: image

### ISSUE THREAD

**Issue by jamaluddinrumi** [ascorbic/unpic-img#77]
i'm afraid it wouldn't noticed

so i make an new one 

from previous issue https://github.com/ascorbic/unpic-img/issues/15, it comes again 

btw, the errors only appear in development

### screenshot
![Screen Shot 2023-03-07 at 9 18 51 PM](https://user-images.githubusercontent.com/446780/223449045-d41ff752-0081-4174-a50f-b0a9c9b344c3.png)

### reproduction
https://github.com/jamaluddinrumi/indomascot.astro/commit/97288b0f7cb5a4e36238d76434ae0863d88e3b2f

**Comment by ascorbic** [comment]
Hi. In your repro you're still using `@unpic/vue@0.0.3`, but the fix was in `0.0.5`. Try upgrading to `latest`

**Comment by jamaluddinrumi** [comment]
finally my devtools not being flooded by that yellow texts anymore 

thank you 

fixed by upgrading to `@unpic/vue@0.0.11` 

![Screen Shot 2023-03-10 at 6 38 44 AM](https://user-images.githubusercontent.com/446780/224185050-d76871dc-489d-43a6-a7f7-bb68207025ee.png)
